google:
  service: GCS
  project: mixup-app
  credentials: <%= Rails.application.credentials.gcskey.to_json %>
  bucket: mixup_app_bucket
google_dev:
  service: GCS
  project: mixup-app
  credentials: <%= Rails.application.credentials.gcskey.to_json %>
  bucket: mixup_app_bucket
